version: '2'
services:
    cv:
        image: olimungo/cv:1.0
        container_name: cv
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
